2023-06-20 12:25:41,578 Job "Lvl2Trader.trade (trigger: cron[day_of_week='mon-fri', hour='16', second='*/10'], next run at: 2023-06-20 16:25:50 UTC)" raised an exception
Traceback (most recent call last):
  File "/Users/mattjzhou/opt/miniconda3/envs/trading_env/lib/python3.11/site-packages/apscheduler/executors/base.py", line 125, in run_job
    retval = job.func(*job.args, **job.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/mattjzhou/riverhill/lvl2_trader.py", line 117, in trade
    if self.trade_shares(symbol, "BUY", "1", time, volume_sum):
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/mattjzhou/riverhill/lvl2_trader.py", line 88, in trade_shares
    self.balance = self.balance - price if action == "BUY" else self.balance + price
                   ~~~~~~~~~~~~~^~~~~~~
TypeError: unsupported operand type(s) for -: 'dict' and 'float'
2023-06-21 12:51:20,459 Job "Lvl2Trader.trade (trigger: cron[day_of_week='mon-fri', hour='16', second='*/10'], next run at: 2023-06-21 16:51:30 UTC)" raised an exception
Traceback (most recent call last):
  File "/Users/mattjzhou/opt/miniconda3/envs/trading_env/lib/python3.11/site-packages/apscheduler/executors/base.py", line 125, in run_job
    retval = job.func(*job.args, **job.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/mattjzhou/riverhill/lvl2_trader.py", line 113, in trade
    volume_sum, df = self.calc_volume_sum(symbol, time, buy_threshold, sell_threshold)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/mattjzhou/riverhill/lvl2_trader.py", line 48, in calc_volume_sum
    df = df[["GetTime", "Side", "Last", "Price", "Dif", "TotalSize"]]
         ~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/mattjzhou/opt/miniconda3/envs/trading_env/lib/python3.11/site-packages/pandas/core/frame.py", line 3767, in __getitem__
    indexer = self.columns._get_indexer_strict(key, "columns")[1]
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/mattjzhou/opt/miniconda3/envs/trading_env/lib/python3.11/site-packages/pandas/core/indexes/base.py", line 5876, in _get_indexer_strict
    self._raise_if_missing(keyarr, indexer, axis_name)
  File "/Users/mattjzhou/opt/miniconda3/envs/trading_env/lib/python3.11/site-packages/pandas/core/indexes/base.py", line 5938, in _raise_if_missing
    raise KeyError(f"{not_found} not in index")
KeyError: "['Last'] not in index"
2023-06-21 12:51:30,433 Job "Lvl2Trader.trade (trigger: cron[day_of_week='mon-fri', hour='16', second='*/10'], next run at: 2023-06-21 16:51:40 UTC)" raised an exception
Traceback (most recent call last):
  File "/Users/mattjzhou/opt/miniconda3/envs/trading_env/lib/python3.11/site-packages/apscheduler/executors/base.py", line 125, in run_job
    retval = job.func(*job.args, **job.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/mattjzhou/riverhill/lvl2_trader.py", line 113, in trade
    volume_sum, df = self.calc_volume_sum(symbol, time, buy_threshold, sell_threshold)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/mattjzhou/riverhill/lvl2_trader.py", line 48, in calc_volume_sum
    df = df[["GetTime", "Side", "Last", "Price", "Dif", "TotalSize"]]
         ~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/mattjzhou/opt/miniconda3/envs/trading_env/lib/python3.11/site-packages/pandas/core/frame.py", line 3767, in __getitem__
    indexer = self.columns._get_indexer_strict(key, "columns")[1]
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/mattjzhou/opt/miniconda3/envs/trading_env/lib/python3.11/site-packages/pandas/core/indexes/base.py", line 5876, in _get_indexer_strict
    self._raise_if_missing(keyarr, indexer, axis_name)
  File "/Users/mattjzhou/opt/miniconda3/envs/trading_env/lib/python3.11/site-packages/pandas/core/indexes/base.py", line 5938, in _raise_if_missing
    raise KeyError(f"{not_found} not in index")
KeyError: "['Last'] not in index"
2023-06-21 12:51:40,437 Job "Lvl2Trader.trade (trigger: cron[day_of_week='mon-fri', hour='16', second='*/10'], next run at: 2023-06-21 16:51:50 UTC)" raised an exception
Traceback (most recent call last):
  File "/Users/mattjzhou/opt/miniconda3/envs/trading_env/lib/python3.11/site-packages/apscheduler/executors/base.py", line 125, in run_job
    retval = job.func(*job.args, **job.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/mattjzhou/riverhill/lvl2_trader.py", line 113, in trade
    volume_sum, df = self.calc_volume_sum(symbol, time, buy_threshold, sell_threshold)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/mattjzhou/riverhill/lvl2_trader.py", line 48, in calc_volume_sum
    df = df[["GetTime", "Side", "Last", "Price", "Dif", "TotalSize"]]
         ~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/mattjzhou/opt/miniconda3/envs/trading_env/lib/python3.11/site-packages/pandas/core/frame.py", line 3767, in __getitem__
    indexer = self.columns._get_indexer_strict(key, "columns")[1]
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/mattjzhou/opt/miniconda3/envs/trading_env/lib/python3.11/site-packages/pandas/core/indexes/base.py", line 5876, in _get_indexer_strict
    self._raise_if_missing(keyarr, indexer, axis_name)
  File "/Users/mattjzhou/opt/miniconda3/envs/trading_env/lib/python3.11/site-packages/pandas/core/indexes/base.py", line 5938, in _raise_if_missing
    raise KeyError(f"{not_found} not in index")
KeyError: "['Last'] not in index"
